typography_spectrum: 0.601602881681174
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.8129618433304131
  lightness: 0.7939844198990613
  saturation: 0.6078731121961027
  rhythmicContrast: 0.013213646598160267
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3302598944865167
analytics:
  google: null
  facebook: null
  twitter: null
name: Australia 2016
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Australia 2016
description: A Family Vacation
purpose: []
