name: Australia 2016
favicon: null
layout_spectrum: 0.8796
typography_spectrum: 0.47837
title: Australia 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2b193'
    - '#7289b3'
    - '#202328'
    - '#475e90'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
