name: Australia 2016
favicon: null
layout_spectrum: 0.1499188137240708
typography_spectrum: 0.2734819552861154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6696064611896873
  lightness: 0.9892092058435082
  saturation: 0.4021142516285181
  rhythmicContrast: 0.1281084732618183
purpose: []
